### ISSUE TITLE
no bmm270 & bmm150 file found

### ISSUE THREAD

**Issue by snailtrailorg** [imliubo/CoreS3-UserDemo#1]
no files in BMI270-sensor-api and BMM150-sensor-api folder.
compiler report error:
src/pages/AppIMU/AppIMUModel.h:8:10: fatal error: bmi270.h: No such file or directory

**Comment by imliubo** [comment]
There has submodules, you need run this command before you complier.
```bash
git submodule update --init --recursive
```
Please try again and thx!

**Comment by imliubo** [comment]
Sorry I found bug... wait a second...

**Comment by imliubo** [comment]
Fix. Pls pull and try...

Thx your report!

**Comment by snailtrailorg** [comment]
great, worked with git clone ...
thanks a ton
